env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-await-in-loop: 0
  no-restricted-syntax: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
